export const PROPERTIES = {
  APPSHEET_APP_ID: "APPSHEET_APP_ID",
  APPSHEET_ACCESS_KEY: "APPSHEET_ACCESS_KEY",
  APPSHEET_REGION: "APPSHEET_REGION",
  APPSHEET_DB_URL: "APPSHEET_DB_URL",
  LOOKER_REPORT_URL: "LOOKER_REPORT_URL",
  LOOKER_EMBED_URL: "LOOKER_EMBED_URL",
  ALERT_DAYS_BEFORE: "ALERT_DAYS_BEFORE",
  EMAIL_SST: "EMAIL_SST",
  LAST_ALERT_RUN: "LAST_ALERT_RUN",
  CD_SYNC_TOKEN: "CD_SYNC_TOKEN",
} as const;
